#
# This file is structured to be consumed by both humans and computers.
# To update the generated Markdown, run `bundle exec rake maintainers:generate`
# To synchronize the maintainers with the github teams, run `bundle exec rake maintainers:synchronize`
# It is a TOML document containing Markdown
#
[Preamble]
  title = "Maintainers"
  text = """
This file lists how the Chef project is maintained. When making changes to the system, this
file tells you who needs to review your patch - you need a simple majority of maintainers
for the relevant subsystems to provide a :+1: on your pull request. Additionally, you need
to not receive a veto from a Lieutenant or the Project Lead.

Check out [How Chef is Maintained](https://github.com/chef/chef-rfc/blob/master/rfc030-maintenance-policy.md#how-the-project-is-maintained) for details on the process, how to become
a maintainer, lieutenant, or the project lead.
"""

[Org]
  [Org.Lead]
    title = "Project Lead"
    person = "adamhjk"

  [Org.Components]
    title = "Components"

    [Org.Components.Core]
      title = "Chef Core"
      team = "client-core"
      text = """
Maintainers for the Chef client, Ohai, mixlibs, ChefDK, ChefSpec, Foodcritic, chefstyle, and sundry others.
"""

      lieutenant = "thommay"

      maintainers = [
        "adamleff",
        "btm",
        "coderanger",
        "danielsdeleo",
        "fujin",
        "jaymzh",
        "jaym",
        "jkeiser",
        "jonlives",
        "jtimberman",
        "lamont-granquist",
        "mcquin",
        "mwrock",
        "ranjib",
        "smurawski",
        "stevendanna",
        "tas50",
        "tduffield",
        "tyler-ball",
        "itmustbejj"
      ]

    [Org.Components.Provisioning]
      title = "Chef Provisioning"
      team = "provisioning"
      text = """
Chef Provisioning and Drivers.  Supported Drivers are listed in the [README](https://github.com/chef/chef-provisioning/blob/master/README.md#chef-provisioning).
"""

      lieutenant = "tyler-ball"

      maintainers = [
        "jkeiser",
        "jjasghar",
        "joaogbcravo",
        "stuartpreston",
        "thehar"
      ]

    [Org.Components.Subsystems]
      title = "Platform Specific Components"
      text = """
The specific components of Chef related to a given platform - including (but not limited to) resources, providers, and the core DSL.
"""

      [Org.Components.Subsystems."Enterprise Linux"]
        title = "Enterprise Linux"
        team = "client-enterprise-linux"

        lieutenant = "jonlives"

        maintainers = [
          "jaymzh",
          "lamont-granquist"
        ]

      [Org.Components.Subsystems.Ubuntu]
        title = "Ubuntu"
        team = "client-ubuntu"

        lieutenant = "ranjib"

        maintainers = [
          "lamont-granquist",
          "tas50",
          "thommay"
        ]

      [Org.Components.Subsystems.Windows]
        title = "Windows"
        team = "client-windows"

        lieutenant = "btm"
        maintainers = [
          "jaym",
          "ksubrama",
          "smurawski",
          "chefsalim",
          "mwrock"
        ]

      [Org.Components.Subsystems.Solaris]
        title = "Solaris"
        team = "client-solaris"

        lieutenant = "thommay"

        maintainers = [
          "lamont-granquist"
        ]

      [Org.Components.Subsystems.AIX]
        title = "AIX"
        team = "client-aix"

        lieutenant = "lamont-granquist"

      [Org.Components.Subsystems."Mac OS X"]
        title = "Mac OS X"
        team = "client-os-x"

        lieutenant = "jtimberman"

        maintainers = [
          "tyler-ball",
          "mikedodge04"
        ]

      [Org.Components.Subsystems.Debian]
        title = "Debian"
        team = "client-debian"

        lieutenant = "thommay"

        maintainers = [
          "lamont-granquist",
          "tas50"
        ]

    [Org.Components.Subsystems.Fedora]
        title = "Fedora"
        team = "client-fedora"

        maintainers = [
          "lamont-granquist"
        ]

      [Org.Components.Subsystems.openSUSE]
        title = "openSUSE"
        team = "client-opensuse"

        maintainers = [
          "lamont-granquist",
          "tas50"
        ]

      [Org.Components.Subsystems."SUSE Enterprise Linux"]
        title = "SUSE Enterprise Linux Server"
        team = "client-suse"

        maintainers = [
          "lamont-granquist"
        ]

      [Org.Components.Subsystems.FreeBSD]
        title = "FreeBSD"
        team = "client-freebsd"

        lieutenant = "martinisoft"

        maintainers = [
          "Aevin1387",
          "tBunnyMan",
          "AgentMeerkat"
        ]

      [Org.Components.Subsystems.OpenBSD]
        title = "OpenBSD"
        team = "client-openbsd"

        lieutenant = "joemiller"

    [Org.Components.Subsystems.Gentoo]
        title = "Gentoo"
        team = "client-gentoo"

        maintainers = [
          "lamont-granquist"
        ]

    [Org.Components.Subsystems.OmniOS]
        title = "OmniOS"
        team = "client-omnios"

        maintainers = [
          "thommay"
        ]

    [Org.Components.Subsystems.ArchLinux]
        title = "ArchLinux"
        team = "client-archlinux"

        maintainers = [
          "lamont-granquist",
          "ryancragun"
        ]

[people]
  [people.adamhjk]
    Name = "Adam Jacob"
    GitHub = "adamhjk"

  [people.adamleff]
    Name = "Adam Leff"
    GitHub = "adamleff"

  [people.Aevin1387]
    Name = "Cory Stephenson"
    GitHub = "Aevin1387"

  [people.AgentMeerkat]
    Name = "Bryant Lippert"
    GitHub = "AgentMeerkat"

  [people.btm]
    Name = "Bryan McLellan"
    GitHub = "btm"

  [people.danielsdeleo]
    Name = "Daniel DeLeo"
    GitHub = "danielsdeleo"

  [people.fujin]
    Name = "AJ Christensen"
    GitHub = "fujin"

  [people.jaymzh]
    Name = "Phil Dibowitz"
    GitHub = "jaymzh"

  [people.jaym]
    Name = "Jay Mundrawala"
    GitHub = "jaym"

  [people.jonlives]
    Name = "Jon Cowie"
    GitHub = "jonlives"

  [people.jtimberman]
    Name = "Joshua Timberman"
    GitHub = "jtimberman"

  [people.lamont-granquist]
    Name = "Lamont Granquist"
    GitHub = "lamont-granquist"

  [people.martinisoft]
    Name = "Aaron Kalin"
    GitHub = "martinisoft"

  [people.mcquin]
    Name = "Claire McQuin"
    GitHub = "mcquin"

  [people.ranjib]
    Name = "Ranjib Dey"
    GitHub = "ranjib"

  [people.sethvargo]
    Name = "Seth Vargo"
    GitHub = "sethvargo"

  [people.smurawski]
    Name = "Steven Murawski"
    GitHub = "smurawski"

  [people.stevendanna]
    Name = "Steven Danna"
    GitHub = "stevendanna"

  [people.tBunnyMan]
    Name = "David Aronsohn"
    GitHub = "tbunnyman"
    IRC = "tBunnyMan"
    Twitter = "OnlyHaveCans"

  [people.thommay]
    Name = "Thom May"
    GitHub = "thommay"
    IRC = "thom"
    Twitter = "thommay"

  [people.tyler-ball]
    Name = "Tyler Ball"
    GitHub = "tyler-ball"

  [people.ksubrama]
    Name = "Kartik Cating-Subramanian"
    GitHub = "ksubrama"

  [people.joemiller]
    Name = "Joe Miller"
    GitHub = "joemiller"

  [people.coderanger]
    Name = "Noah Kantrowitz"
    GitHub = "coderanger"

  [people.ryancragun]
    Name = "Ryan Cragun"
    GitHub = "ryancragun"

  [people.chefsalim]
    Name = "Salim Alam"
    GitHub = "chefsalim"

  [people.mwrock]
    Name = "Matt Wrock"
    GitHub = "mwrock"

  [people.tas50]
    Name = "Tim Smith"
    GitHub = "tas50"
    Twitter = "tas50"
    IRC = "tas50"

  [people.jkeiser]
    Name = "John Keiser"
    GitHub = "jkeiser"

  [people.stuartpreston]
    Name = "Stuart Preston"
    GitHub = "stuartpreston"

  [people.jjasghar]
    Name = "JJ Asghar"
    GitHub = "jjasghar"
    Twitter = "jjasghar"
    IRC = "j^2"

  [people.joaogbcravo]
    Name = "Jo√£o Cravo"
    GitHub = "joaogbcravo"
    Twitter = "joaogbcravo"

  [people.thehar]
    Name = "Harley Alaniz"
    GitHub = "thehar"

  [people.tduffield]
    Name = "Tom Duffield"
    GitHub = "tduffield"

  [people.mikedodge04]
    Name = "mikedodge04"
    GitHub = "mikedodge04"
    Twitter = "mikedodge04"
    IRC = "mikedodge04"

  [people.itmustbejj]
    Name = "Josh Hudson"
    GitHub = "itmustbejj"
    Twitter = "itmustbejj"
    IRC = "itmustbejj"
